version: "3.9"
services:
  app:
    build: ./app
    container_name: three-tier-app_app
    environment:
      - NODE_ENV=production
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=appuser
      - PGPASSWORD=apppass
      - PGDATABASE=appdb
    networks:
      - appnet
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: three-tier-app_web
    ports:
      - "8080:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: three-tier-app_db
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppass
      - POSTGRES_DB=appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge

volumes:
  db_data:
